name: Update Junghaie games

on:
  workflow_dispatch:

  schedule:
    - cron: "17 3 * * *"

permissions:
  contents: write

jobs:
  update-games:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Chromium
        run: npx playwright install --with-deps chromium

      - name: Scrape all games
        run: npm run scrape

      - name: Show games.json
        run: cat data/games.json

      - name: Commit updated games
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/games.json

          if git diff --cached --quiet; then
            echo "Keine Änderungen."
          else
            git commit -m "Update games"
            git push
          fi
